"""Self-contained HTML report.

The CSS is inlined and there are no external requests, so a report can be
attached to an email or dropped into an evidence bundle and still render years
later on a machine with no network.

Markup is built in Python rather than in a template language. The report has
one shape; expressing its conditionals as code keeps them testable and keeps
the dependency list at one package.
"""

from __future__ import annotations

from collections.abc import Iterable, Sequence

from harness.analysis.baseline import NoiseFinding
from harness.analysis.coverage import CoverageReport
from harness.analysis.diff import RunDiff
from harness.analysis.gates import GateOutcome
from harness.core.models import CaseResult, Outcome, RunRecord
from harness.core.timeutil import format_duration, to_iso
from harness.reporting.template import escape, load_template, render

__all__ = ["render_html"]

_OUTCOME_ORDER = (
    Outcome.DETECTED,
    Outcome.VISIBLE,
    Outcome.BLIND,
    Outcome.ERROR,
    Outcome.SKIPPED,
)
_OUTCOME_LABEL = {
    Outcome.DETECTED: "Detected",
    Outcome.VISIBLE: "Detection gap",
    Outcome.BLIND: "Visibility gap",
    Outcome.ERROR: "Errored",
    Outcome.SKIPPED: "Skipped",
}


def render_html(
    run: RunRecord,
    *,
    coverage: CoverageReport | None = None,
    gates: GateOutcome | None = None,
    diff: RunDiff | None = None,
    noise: Sequence[NoiseFinding] = (),
) -> str:
    summary = run.summarise()
    passed = gates is None or gates.passed

    context = {
        "title": f"Detection validation - {run.profile} - {run.run_id}",
        "heading": f"Detection validation: {run.profile}",
        "verdict": "PASS" if passed else "FAIL",
        "verdict_class": "pass" if passed else "fail",
        "subtitle": (
            f"{run.run_id} - backend {run.backend} - {run.mode} mode - "
            f"started {to_iso(run.started_at)} - "
            f"took {format_duration(run.duration_seconds)}"
        ),
        "style": load_template("report.css"),
        "tiles": _tiles(summary),
        "outcome_bar": _outcome_bar(summary),
        "gates": _gates(gates),
        "changes": _changes(diff),
        "detection_gaps": _gap_table(
            "Detection gaps",
            run.gaps("detection"),
            "The telemetry arrived and the rule did not fire. Owned by detection "
            "engineering: the rule needs work, not the log pipeline.",
        ),
        "visibility_gaps": _gap_table(
            "Visibility gaps",
            run.gaps("visibility"),
            "The telemetry never arrived. Owned by the platform team: tuning the "
            "rule cannot help until the source is collected.",
        ),
        "noise": _noise(noise),
        "coverage": _coverage(coverage),
        "cases": _cases(run.results),
        "footer": (
            f"Generated by the detection validation pipeline - operator {run.operator} - "
            f"rule library {run.git_ref or 'unknown'}"
        ),
    }
    return render(load_template("report.html"), context)


# ------------------------------------------------------------------ sections


def _tiles(summary) -> str:
    detected = summary.by_outcome.get("detected", 0)
    visible = summary.by_outcome.get("visible", 0)
    blind = summary.by_outcome.get("blind", 0)

    tiles = [
        _tile("Cases", str(summary.total), f"{summary.techniques_total} techniques"),
        _tile(
            "Detected",
            str(detected),
            f"{summary.detection_rate:.0%} of scoreable",
            css="detected",
        ),
        _tile("Detection gaps", str(visible), "rule did not fire", css="visible"),
        _tile("Visibility gaps", str(blind), "telemetry missing", css="blind"),
        _tile("Telemetry visibility", f"{summary.visibility_rate:.0%}", "of scoreable cases"),
    ]
    if summary.latency_p50 is not None:
        tiles.append(
            _tile(
                "Detect latency",
                format_duration(summary.latency_p50),
                f"p95 {format_duration(summary.latency_p95)}",
            )
        )
    if summary.noisy_rules:
        tiles.append(_tile("Noisy rules", str(summary.noisy_rules), "fire on baseline"))

    return f'<div class="tiles">{"".join(tiles)}</div>'


def _tile(label: str, value: str, sub: str = "", *, css: str = "") -> str:
    classes = f"tile {css}".strip()
    return (
        f'<div class="{classes}"><div class="label">{escape(label)}</div>'
        f'<div class="value">{escape(value)}</div>'
        f'<div class="sub">{escape(sub)}</div></div>'
    )


def _outcome_bar(summary) -> str:
    total = summary.total or 1
    segments = []
    legend = []
    for outcome in _OUTCOME_ORDER:
        count = summary.by_outcome.get(outcome.value, 0)
        if not count:
            continue
        width = count / total * 100
        segments.append(
            f'<span class="s-{outcome.value}" style="width:{width:.2f}%" '
            f'title="{escape(_OUTCOME_LABEL[outcome])}: {count}"></span>'
        )
        legend.append(
            f'<span><i class="s-{outcome.value}" style="background:var(--{outcome.value})"></i>'
            f"{escape(_OUTCOME_LABEL[outcome])} ({count})</span>"
        )
    if not segments:
        return ""
    return (
        f'<div class="bar">{"".join(segments)}</div>'
        f'<div class="legend">{"".join(legend)}</div>'
    )


def _gates(gates: GateOutcome | None) -> str:
    if gates is None:
        return ""
    rows = []
    for gate in gates.results:
        if not gate.applicable:
            rows.append(
                f'<div class="gate"><span class="pill skipped">n/a</span>'
                f'<span class="name">{escape(gate.name)}</span>'
                f'<span class="detail">not configured</span></div>'
            )
            continue
        pill = "pass" if gate.passed else "fail"
        offenders = ""
        if gate.offenders:
            items = "".join(f"<li>{escape(o)}</li>" for o in gate.offenders[:8])
            extra = (
                f"<li>...and {len(gate.offenders) - 8} more</li>"
                if len(gate.offenders) > 8
                else ""
            )
            offenders = f"<ul>{items}{extra}</ul>"
        rows.append(
            f'<div class="gate"><span class="pill {pill}">{pill}</span>'
            f'<span class="name">{escape(gate.name)}</span>'
            f'<span class="detail">{escape(gate.message)}{offenders}</span></div>'
        )
    return f"<h2>Gates</h2>{''.join(rows)}"


def _changes(diff: RunDiff | None) -> str:
    if diff is None or not diff.changed:
        return ""
    header = "<h2>Changes since the previous run</h2>"
    if diff.baseline_run_id:
        header += f'<p class="note">Compared against <code>{escape(diff.baseline_run_id)}</code>.</p>'
    rows = "".join(
        "<tr>"
        f'<td><span class="pill {_delta_pill(d.kind.value)}">{escape(d.kind.value)}</span></td>'
        f"<td><code>{escape(d.rule_name)}</code></td>"
        f"<td><code>{escape(d.emulation_id)}</code></td>"
        f"<td>{escape(d.before.value if d.before else '-')}</td>"
        f"<td>{escape(d.after.value if d.after else '-')}</td>"
        f'<td class="note">{escape(d.note)}</td>'
        "</tr>"
        for d in diff.changed[:40]
    )
    return (
        f"{header}<div class='table-wrap'><table><thead><tr>"
        "<th>Change</th><th>Rule</th><th>Test</th><th>Before</th><th>After</th><th>Note</th>"
        f"</tr></thead><tbody>{rows}</tbody></table></div>"
    )


def _delta_pill(kind: str) -> str:
    return {
        "regression": "blind",
        "improvement": "detected",
        "slower": "visible",
        "new": "skipped",
        "removed": "skipped",
    }.get(kind, "skipped")


def _gap_table(title: str, results: Iterable[CaseResult], preamble: str) -> str:
    results = sorted(results, key=lambda r: (-r.case.severity.rank, r.case.rule_name))
    if not results:
        return f'<h2>{escape(title)}</h2><p class="empty">None.</p>'

    rows = []
    for result in results:
        accepted = result.status.value == "pass"
        note = result.notes[0] if result.notes else ""
        rows.append(
            "<tr>"
            f"<td><code>{escape(result.case.rule_name)}</code></td>"
            f"<td>{escape(result.case.severity.value)}</td>"
            f"<td>{escape(', '.join(result.case.technique_ids) or '-')}</td>"
            f"<td><code>{escape(result.case.emulation_id)}</code></td>"
            f"<td>{escape(', '.join(result.case.telemetry) or '-')}</td>"
            f'<td><span class="pill {"pass" if accepted else "fail"}">'
            f'{"accepted" if accepted else "unexpected"}</span></td>'
            f'<td class="note">{escape(note)}</td>'
            "</tr>"
        )
    return (
        f"<h2>{escape(title)} ({len(results)})</h2>"
        f'<p class="note">{escape(preamble)}</p>'
        "<div class='table-wrap'><table><thead><tr>"
        "<th>Rule</th><th>Severity</th><th>Technique</th><th>Test</th>"
        "<th>Telemetry</th><th>Expected?</th><th>Note</th>"
        f"</tr></thead><tbody>{''.join(rows)}</tbody></table></div>"
    )


def _noise(noise: Sequence[NoiseFinding]) -> str:
    if not noise:
        return ""
    rows = "".join(
        "<tr>"
        f"<td><code>{escape(n.rule)}</code></td>"
        f'<td class="num">{n.hits}</td>'
        f'<td class="num">{n.allowance}</td>'
        f'<td class="num">{n.excess}</td>'
        f"<td>{escape(n.severity)}</td>"
        f"<td>{escape(n.profile or '-')}</td>"
        "</tr>"
        for n in noise
    )
    return (
        "<h2>Baseline noise</h2>"
        '<p class="note">These rules matched activity in a window where nothing '
        "was emulated. A rule can be detected and noisy at the same time; both "
        "need fixing.</p>"
        "<div class='table-wrap'><table><thead><tr><th>Rule</th>"
        '<th class="num">Hits</th><th class="num">Accepted</th>'
        '<th class="num">Over</th><th>Severity</th><th>Profile</th>'
        f"</tr></thead><tbody>{rows}</tbody></table></div>"
    )


def _coverage(coverage: CoverageReport | None) -> str:
    if coverage is None or not coverage.tactics:
        return ""

    rows = []
    for tactic in sorted(coverage.tactics.values(), key=lambda t: t.order):
        if not tactic.scoreable:
            continue
        rows.append(
            "<tr>"
            f"<td>{escape(tactic.name or tactic.tactic)}</td>"
            f"<td>{escape(tactic.priority)}</td>"
            f'<td class="num">{tactic.scoreable}</td>'
            f"<td>{_meter(tactic.detection_rate, tactic.target_detected)}</td>"
            f'<td class="num">{tactic.detection_rate:.0%}</td>'
            f"<td>{_meter(tactic.visibility_rate, tactic.target_visible)}</td>"
            f'<td class="num">{tactic.visibility_rate:.0%}</td>'
            f'<td><span class="pill {"pass" if tactic.meets_target else "fail"}">'
            f'{"on target" if tactic.meets_target else "below"}</span></td>'
            "</tr>"
        )

    technique_rows = []
    for technique in coverage.by_priority()[:40]:
        if not technique.scoreable:
            continue
        technique_rows.append(
            "<tr>"
            f"<td><code>{escape(technique.technique)}</code></td>"
            f"<td>{escape(technique.name)}</td>"
            f"<td>{escape(technique.priority)}</td>"
            f'<td class="num">{technique.detected}</td>'
            f'<td class="num">{technique.visible}</td>'
            f'<td class="num">{technique.blind}</td>'
            f'<td><span class="pill {_status_pill(technique.status)}">'
            f"{escape(technique.status)}</span></td>"
            f'<td class="note">{escape(", ".join(technique.missing_telemetry))}</td>'
            "</tr>"
        )

    detail = (
        "<details><summary>Per-technique detail</summary>"
        "<div class='table-wrap'><table><thead><tr><th>Technique</th><th>Name</th>"
        '<th>Priority</th><th class="num">Det</th><th class="num">Vis</th>'
        '<th class="num">Blind</th><th>Status</th><th>Missing telemetry</th>'
        f"</tr></thead><tbody>{''.join(technique_rows)}</tbody></table></div></details>"
    )

    return (
        "<h2>ATT&amp;CK coverage</h2>"
        "<div class='table-wrap'><table><thead><tr><th>Tactic</th><th>Priority</th>"
        '<th class="num">Cases</th><th>Detection</th><th class="num">%</th>'
        '<th>Visibility</th><th class="num">%</th><th></th>'
        f"</tr></thead><tbody>{''.join(rows)}</tbody></table></div>{detail}"
    )


def _status_pill(status: str) -> str:
    return {
        "covered": "detected",
        "partial": "visible",
        "detection-gap": "visible",
        "visibility-gap": "blind",
        "untested": "skipped",
    }.get(status, "skipped")


def _meter(actual: float, target: float) -> str:
    """A bar with a tick marking the target, so "below" is visible at a glance."""
    below = "" if actual >= target else " below"
    return (
        f'<div class="meter{below}"><b style="width:{max(0.0, min(1.0, actual)) * 100:.1f}%"></b>'
        f'<i style="left:{max(0.0, min(1.0, target)) * 100:.1f}%"></i></div>'
    )


def _cases(results: Sequence[CaseResult]) -> str:
    ordered = sorted(
        results,
        key=lambda r: (
            _OUTCOME_ORDER.index(r.outcome) if r.outcome in _OUTCOME_ORDER else 9,
            -r.case.severity.rank,
            r.case.rule_name,
        ),
    )
    rows = []
    for result in ordered:
        notes = " ".join(result.notes)
        if len(notes) > 160:
            notes = notes[:157] + "..."
        rows.append(
            "<tr>"
            f"<td><code>{escape(result.case.rule_name)}</code></td>"
            f"<td>{escape(', '.join(result.case.technique_ids) or '-')}</td>"
            f"<td><code>{escape(result.case.emulation_id)}</code></td>"
            f'<td><span class="pill {result.outcome.value}">'
            f"{escape(result.outcome.value)}</span></td>"
            f'<td><span class="pill {result.status.value}">'
            f"{escape(result.status.value)}</span></td>"
            f"<td>{escape(result.confidence.value)}</td>"
            f'<td class="num">{result.detection_hits}</td>'
            f'<td class="num">{result.telemetry_hits}</td>'
            f'<td class="num">{escape(format_duration(result.latency_seconds))}</td>'
            f'<td class="note">{escape(notes)}</td>'
            "</tr>"
        )
    return (
        "<h2>All cases</h2><div class='table-wrap'><table><thead><tr>"
        "<th>Rule</th><th>Technique</th><th>Test</th><th>Outcome</th><th>Status</th>"
        '<th>Confidence</th><th class="num">Hits</th><th class="num">Telem</th>'
        '<th class="num">Latency</th><th>Notes</th>'
        f"</tr></thead><tbody>{''.join(rows)}</tbody></table></div>"
    )
