#!/usr/bin/env python3
"""Render systemd drop-ins from ``scheduler/jobs.yml``.

The templated units in ``scheduler/systemd/`` carry a default schedule and a
default (non-executing) command line. Everything that differs per profile - when
it runs, and whether it is allowed to emulate - belongs in a drop-in, because
overriding a template by editing it breaks every other instance.

Keeping those drop-ins hand-written would mean the schedule lives in two places
and drifts, so this script generates them from ``scheduler/jobs.yml``, which is
the reviewable source of truth::

    python scripts/render_systemd.py            # write, and say what changed
    python scripts/render_systemd.py --check    # fail if the tree is stale (CI)
    python scripts/render_systemd.py --stdout   # print without writing

The generated files are committed. That is deliberate: an operator installing
the units on a host should not need this repository's Python environment, and a
reviewer should see the schedule change in the diff of the pull request that
changes it.

What this script does *not* do is grant any authority. A job marked
``execute: true`` renders a drop-in that passes ``--execute``, but the run still
refuses unless the safety policy independently authorises it - see
``harness/emulation/safety.py`` and ``docs/threat-model.md``. The manifest is
documentation; the policy is the control.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
JOBS = REPO_ROOT / "scheduler" / "jobs.yml"
UNITS = REPO_ROOT / "scheduler" / "systemd"
GENERATED = UNITS / "generated"

#: Exit codes match the CLI's, so a Makefile or CI step can treat this script
#: like any other stage of the pipeline. See harness/core/errors.py.
EXIT_OK = 0
EXIT_STALE = 1
EXIT_USAGE = 2
EXIT_CONFIG = 3

BANNER = (
    "# Generated by scripts/render_systemd.py from scheduler/jobs.yml.\n"
    "# Do not edit: run the script instead, and commit the result.\n"
)

#: ``HH:MM``
_TIME = re.compile(r"^(\d{1,2}):(\d{2})$")
#: ``Sun 03:00`` - weekday plus time, no date component.
_DAY_TIME = re.compile(r"^([A-Za-z]{3}(?:\.\.[A-Za-z]{3})?(?:,[A-Za-z]{3})*)\s+(\d{1,2}):(\d{2})$")


class ManifestError(Exception):
    """The manifest cannot be rendered into units."""


def display(path: Path) -> str:
    """Repository-relative where possible, absolute otherwise (``--output``)."""
    try:
        return path.relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return path.as_posix()


@dataclass(frozen=True)
class Rendered:
    """One drop-in file: where it goes, and what is in it."""

    path: Path
    content: str

    @property
    def relative(self) -> str:
        return display(self.path)


# ----------------------------------------------------------------- schedules


def to_oncalendar(schedule: str) -> str:
    """Translate a manifest schedule into a systemd ``OnCalendar=`` expression.

    The manifest uses the shortest form that is unambiguous to a human reading
    the job list - ``02:15``, ``Sun 03:00`` - because that file is read far more
    often than it is installed. systemd wants a full calendar expression, and
    silently accepts some malformed ones as "never", so the translation is
    explicit and anything unrecognised is refused rather than guessed at.
    """
    value = schedule.strip()
    if not value:
        raise ManifestError("schedule is empty")

    match = _TIME.match(value)
    if match:
        hour, minute = match.groups()
        return f"*-*-* {int(hour):02d}:{minute}:00"

    match = _DAY_TIME.match(value)
    if match:
        weekday, hour, minute = match.groups()
        return f"{weekday} *-*-* {int(hour):02d}:{minute}:00"

    # Anything else must already be a calendar expression: a date component
    # ('Mon *-*-01..07 04:00'), or a systemd shorthand ('daily', 'weekly').
    if value in {"minutely", "hourly", "daily", "weekly", "monthly", "quarterly", "yearly"}:
        return value
    if "-" in value or "*" in value:
        # Add the seconds field if the expression stops at minutes; systemd
        # defaults it to :00, but being explicit keeps `systemd-analyze
        # calendar` output identical to what is written here.
        return value if re.search(r":\d{2}:\d{2}\b", value) else f"{value}:00"

    raise ManifestError(
        f"unrecognised schedule {schedule!r}: use 'HH:MM', 'Day HH:MM', "
        "or a full systemd calendar expression"
    )


# ------------------------------------------------------------------ rendering


def load_jobs(path: Path = JOBS) -> dict[str, Any]:
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ManifestError(f"{path} does not exist") from exc
    except yaml.YAMLError as exc:
        raise ManifestError(f"{path} is not valid YAML: {exc}") from exc
    if not isinstance(data, dict) or not isinstance(data.get("jobs"), list):
        raise ManifestError(f"{path} has no 'jobs:' list")
    return data


def known_profiles(root: Path = REPO_ROOT) -> set[str]:
    return {p.stem for p in (root / "config" / "profiles").glob("*.yml")}


def render(manifest: dict[str, Any], *, profiles: set[str] | None = None) -> list[Rendered]:
    """Render every timer-triggered job in the manifest.

    CI-triggered jobs are skipped: those run in a workflow, not on a host with
    systemd, and emitting a timer for them would put a schedule on disk that
    nothing owns.
    """
    if profiles is None:
        profiles = known_profiles()
    defaults = manifest.get("defaults") or {}
    out: list[Rendered] = []
    seen: dict[str, str] = {}

    for index, job in enumerate(manifest.get("jobs") or []):
        if not isinstance(job, dict):
            raise ManifestError(f"job #{index + 1} is not a mapping")
        name = job.get("name") or f"job #{index + 1}"
        if job.get("trigger") != "timer":
            continue

        profile = job.get("profile")
        if not profile:
            raise ManifestError(f"{name}: timer job has no profile")
        if profiles and profile not in profiles:
            raise ManifestError(f"{name}: profile {profile!r} does not exist in config/profiles/")
        # One timer per instance. Two jobs on the same profile would render two
        # files at the same path, and the second would silently win.
        if profile in seen:
            raise ManifestError(
                f"{name}: profile {profile!r} is already scheduled by {seen[profile]!r}; "
                "systemd template instances are keyed on the profile name"
            )
        seen[profile] = name

        schedule = job.get("schedule")
        if not schedule:
            raise ManifestError(f"{name}: timer job has no schedule")
        try:
            oncalendar = to_oncalendar(str(schedule))
        except ManifestError as exc:
            raise ManifestError(f"{name}: {exc}") from exc

        out.append(_timer_dropin(job, profile=profile, oncalendar=oncalendar))

        execute = bool(job.get("execute", defaults.get("execute", False)))
        if execute:
            if not job.get("authorization"):
                # The safety policy would refuse this at run time anyway. Failing
                # here means it is caught in review instead of at 03:00 on Sunday.
                raise ManifestError(f"{name}: execute: true requires an authorization reference")
            out.append(_service_dropin(job, profile=profile, defaults=defaults))

    return out


def _timer_dropin(job: dict[str, Any], *, profile: str, oncalendar: str) -> Rendered:
    description = _one_line(job.get("description"))
    body = [
        BANNER,
        f"# {job.get('name')}: {description}\n" if description else "",
        "\n[Timer]\n",
        "# The empty assignment clears the template's default. Without it the two\n"
        "# schedules are additive and the job runs twice.\n",
        "OnCalendar=\n",
        f"OnCalendar={oncalendar}\n",
    ]
    return Rendered(
        path=GENERATED / f"dvp-validation@{profile}.timer.d" / "schedule.conf",
        content="".join(part for part in body if part),
    )


def _service_dropin(job: dict[str, Any], *, profile: str, defaults: dict[str, Any]) -> Rendered:
    backend = job.get("backend", defaults.get("backend", "fixture"))
    formats = job.get("formats") or defaults.get("formats") or []
    format_args = "".join(f" --format {fmt}" for fmt in formats)
    command = (
        f"/opt/dvp/.venv/bin/dvp --log-format json run --profile {profile} "
        f"--backend {backend}{format_args} --execute"
    )
    body = [
        BANNER,
        f"#\n# Authorisation of record: {job.get('authorization')}\n",
        "#\n"
        "# --execute only makes the request. The run still refuses unless the\n"
        "# safety policy authorises it independently: an authorisation reference\n"
        "# in settings, a non-empty host allowlist, and a technique that is not\n"
        "# denylisted. See docs/threat-model.md.\n",
        "\n[Service]\n",
        "ExecStart=\n",
        f"ExecStart={command}\n",
    ]
    return Rendered(
        path=GENERATED / f"dvp-validation@{profile}.service.d" / "execute.conf",
        content="".join(body),
    )


def _one_line(text: Any) -> str:
    return " ".join(str(text).split()) if text else ""


# --------------------------------------------------------------------- output


def write(rendered: list[Rendered], *, root: Path = GENERATED) -> list[str]:
    """Write the drop-ins, removing any generated file no longer in the manifest.

    A job deleted from the manifest must take its timer with it, or the host
    keeps running a schedule that nobody can find the source of.
    """
    wanted = {r.path for r in rendered}
    changed: list[str] = []

    for stale in sorted(root.rglob("*.conf")):
        if stale not in wanted:
            stale.unlink()
            changed.append(f"removed  {display(stale)}")
    for directory in sorted(root.glob("*.d"), reverse=True):
        if directory.is_dir() and not any(directory.iterdir()):
            directory.rmdir()

    for item in rendered:
        existing = item.path.read_text(encoding="utf-8") if item.path.exists() else None
        if existing == item.content:
            continue
        item.path.parent.mkdir(parents=True, exist_ok=True)
        item.path.write_text(item.content, encoding="utf-8")
        changed.append(f"{'wrote   ' if existing is None else 'updated '}{item.relative}")

    return changed


def drift(rendered: list[Rendered], *, root: Path = GENERATED) -> list[str]:
    """Differences between the manifest and what is committed, as messages."""
    problems: list[str] = []
    wanted = {r.path for r in rendered}
    for item in rendered:
        if not item.path.exists():
            problems.append(f"missing:   {item.relative}")
        elif item.path.read_text(encoding="utf-8") != item.content:
            problems.append(f"stale:     {item.relative}")
    for existing in sorted(root.rglob("*.conf")):
        if existing not in wanted:
            problems.append(f"orphaned:  {display(existing)}")
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--jobs", type=Path, default=JOBS, help="manifest path")
    parser.add_argument("--output", type=Path, default=GENERATED, help="where to write drop-ins")
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if the committed drop-ins differ from the manifest",
    )
    parser.add_argument("--stdout", action="store_true", help="print the drop-ins and exit")
    args = parser.parse_args(argv)

    if args.check and args.stdout:
        parser.error("--check and --stdout are mutually exclusive")

    try:
        rendered = render(load_jobs(args.jobs))
    except ManifestError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return EXIT_CONFIG

    if not rendered:
        print("no timer-triggered jobs in the manifest; nothing to render", file=sys.stderr)
        return EXIT_OK

    if args.stdout:
        for item in rendered:
            print(f"# ---- {item.relative}")
            print(item.content)
        return EXIT_OK

    if args.check:
        problems = drift(rendered, root=args.output)
        if problems:
            print(
                "scheduler/systemd/generated/ does not match scheduler/jobs.yml:",
                file=sys.stderr,
            )
            for problem in problems:
                print(f"  {problem}", file=sys.stderr)
            print("\nrun: python scripts/render_systemd.py", file=sys.stderr)
            return EXIT_STALE
        print(f"{len(rendered)} drop-in(s) match the manifest")
        return EXIT_OK

    changed = write(rendered, root=args.output)
    for line in changed:
        print(line)
    print(f"{len(rendered)} drop-in(s) rendered, {len(changed)} changed")
    return EXIT_OK


if __name__ == "__main__":  # pragma: no cover
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:  # pragma: no cover
        raise SystemExit(130) from None
